<option>note</option>
<option>logo-db</option>
<option>music</option>
<option>search</option>
<option>flashlight</option>
<option>mail</option>
<option>heart</option>
<option>heart-empty</option>
<option>star</option>
<option>star-empty</option>
<option>user</option>
<option>users</option>
<option>user-add</option>
<option>video</option>
<option>picture</option>
<option>camera</option>
<option>layout</option>
<option>menu</option>
<option>check</option>
<option>cancel</option>
<option>cancel-circled</option>
<option>cancel-squared</option>
<option>plus</option>
<option>plus-circled</option>
<option>plus-squared</option>
<option>minus</option>
<option>minus-circled</option>
<option>minus-squared</option>
<option>help</option>
<option>help-circled</option>
<option>info</option>
<option>info-circled</option>
<option>back</option>
<option>home</option>
<option>link</option>
<option>attach</option>
<option>lock</option>
<option>lock-open</option>
<option>eye</option>
<option>tag</option>
<option>bookmark</option>
<option>bookmarks</option>
<option>flag</option>
<option>thumbs-up</option>
<option>thumbs-down</option>
<option>download</option>
<option>upload</option>
<option>upload-cloud</option>
<option>reply</option>
<option>reply-all</option>
<option>forward</option>
<option>quote</option>
<option>code</option>
<option>export</option>
<option>pencil</option>
<option>feather</option>
<option>print</option>
<option>retweet</option>
<option>keyboard</option>
<option>comment</option>
<option>chat</option>
<option>bell</option>
<option>attention</option>
<option>alert</option>
<option>vcard</option>
<option>address</option>
<option>location</option>
<option>map</option>
<option>direction</option>
<option>compass</option>
<option>cup</option>
<option>trash</option>
<option>doc</option>
<option>docs</option>
<option>doc-landscape</option>
<option>doc-text</option>
<option>doc-text-inv</option>
<option>newspaper</option>
<option>book-open</option>
<option>book</option>
<option>folder</option>
<option>archive</option>
<option>box</option>
<option>rss</option>
<option>phone</option>
<option>cog</option>
<option>tools</option>
<option>share</option>
<option>shareable</option>
<option>basket</option>
<option>bag</option>
<option>calendar</option>
<option>login</option>
<option>logout</option>
<option>mic</option>
<option>mute</option>
<option>sound</option>
<option>volume</option>
<option>clock</option>
<option>hourglass</option>
<option>lamp</option>
<option>light-down</option>
<option>light-up</option>
<option>adjust</option>
<option>block</option>
<option>resize-full</option>
<option>resize-small</option>
<option>popup</option>
<option>publish</option>
<option>window</option>
<option>arrow-combo</option>
<option>down-circled</option>
<option>left-circled</option>
<option>right-circled</option>
<option>up-circled</option>
<option>down-open</option>
<option>left-open</option>
<option selected>right-open</option>
<option>up-open</option>
<option>down-open-mini</option>
<option>left-open-mini</option>
<option>right-open-mini</option>
<option>up-open-mini</option>
<option>down-open-big</option>
<option>left-open-big</option>
<option>right-open-big</option>
<option>up-open-big</option>
<option>down</option>
<option>left</option>
<option>right</option>
<option>up</option>
<option>down-dir</option>
<option>left-dir</option>
<option>right-dir</option>
<option>up-dir</option>
<option>down-bold</option>
<option>left-bold</option>
<option>right-bold</option>
<option>up-bold</option>
<option>down-thin</option>
<option>left-thin</option>
<option>right-thin</option>
<option>note-beamed</option>
<option>ccw</option>
<option>cw</option>
<option>arrows-ccw</option>
<option>level-down</option>
<option>level-up</option>
<option>shuffle</option>
<option>loop</option>
<option>switch</option>
<option>play</option>
<option>stop</option>
<option>pause</option>
<option>record</option>
<option>to-end</option>
<option>to-start</option>
<option>fast-forward</option>
<option>fast-backward</option>
<option>progress-0</option>
<option>progress-1</option>
<option>progress-2</option>
<option>progress-3</option>
<option>target</option>
<option>palette</option>
<option>list</option>
<option>list-add</option>
<option>signal</option>
<option>trophy</option>
<option>battery</option>
<option>back-in-time</option>
<option>monitor</option>
<option>mobile</option>
<option>network</option>
<option>cd</option>
<option>inbox</option>
<option>install</option>
<option>globe</option>
<option>cloud</option>
<option>cloud-thunder</option>
<option>flash</option>
<option>moon</option>
<option>flight</option>
<option>paper-plane</option>
<option>leaf</option>
<option>lifebuoy</option>
<option>mouse</option>
<option>briefcase</option>
<option>suitcase</option>
<option>dot</option>
<option>dot-2</option>
<option>dot-3</option>
<option>brush</option>
<option>magnet</option>
<option>infinity</option>
<option>erase</option>
<option>chart-pie</option>
<option>chart-line</option>
<option>chart-bar</option>
<option>chart-area</option>
<option>tape</option>
<option>graduation-cap</option>
<option>language</option>
<option>ticket</option>
<option>water</option>
<option>droplet</option>
<option>air</option>
<option>credit-card</option>
<option>floppy</option>
<option>clipboard</option>
<option>megaphone</option>
<option>database</option>
<option>drive</option>
<option>bucket</option>
<option>thermometer</option>
<option>key</option>
<option>flow-cascade</option>
<option>flow-branch</option>
<option>flow-tree</option>
<option>flow-line</option>
<option>flow-parallel</option>
<option>rocket</option>
<option>gauge</option>
<option>traffic-cone</option>
<option>cc</option>
<option>cc-by</option>
<option>cc-nc</option>
<option>cc-nc-eu</option>
<option>cc-nc-jp</option>
<option>cc-sa</option>
<option>cc-nd</option>
<option>cc-pd</option>
<option>cc-zero</option>
<option>cc-share</option>
<option>cc-remix</option>
<option>github</option>
<option>github-circled</option>
<option>flickr</option>
<option>flickr-circled</option>
<option>vimeo</option>
<option>vimeo-circled</option>
<option>twitter</option>
<option>twitter-circled</option>
<option>facebook</option>
<option>facebook-circled</option>
<option>facebook-squared</option>
<option>gplus</option>
<option>gplus-circled</option>
<option>pinterest</option>
<option>pinterest-circled</option>
<option>tumblr</option>
<option>tumblr-circled</option>
<option>linkedin</option>
<option>linkedin-circled</option>
<option>dribbble</option>
<option>dribbble-circled</option>
<option>stumbleupon</option>
<option>stumbleupon-circled</option>
<option>lastfm</option>
<option>lastfm-circled</option>
<option>rdio</option>
<option>rdio-circled</option>
<option>spotify</option>
<option>spotify-circled</option>
<option>qq</option>
<option>instagram</option>
<option>dropbox</option>
<option>evernote</option>
<option>flattr</option>
<option>skype</option>
<option>skype-circled</option>
<option>renren</option>
<option>sina-weibo</option>
<option>paypal</option>
<option>picasa</option>
<option>soundcloud</option>
<option>mixi</option>
<option>behance</option>
<option>google-circles</option>
<option>vkontakte</option>
<option>smashing</option>
<option>sweden</option>
<option>db-shape</option>
<option>up-thin</option>